Learning site/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using Learning_site.Models;
using System.IO;

namespace Learning_site.Controllers
{
    public class AssignmentController : Controller
    {
        private ApplicationDbContext _context;

        public AssignmentController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Assignment

  

          //  [Route("Assignment/{Id}")]

        public ActionResult Index(int Id)
        {


            Session["CourseID"] = Id;
            string currentUserId = User.Identity.GetUserId();

            var Assignments = _context.Assignments.Where(c => c.studentId == currentUserId).Where(c=>c.courseId== Id).ToList();

            
            return View(Assignments);


        }




        // GET: Assignment/Create
        public ActionResult Create()
        {


            return View();
        }
        // POST: Assignment/Create
        [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult Create(Assignment assignment,HttpPostedFileBase uploadAssign)
        {

           string path = Path.Combine(Server.MapPath("~/upload/Assignments"), uploadAssign.FileName);
           uploadAssign.SaveAs(path);
            string currentUserId = User.Identity.GetUserId();
           assignment.File = uploadAssign.FileName;
            assignment.courseId = (int)Session["CourseID"];

            assignment.studentId = currentUserId;
                _context.Assignments.Add(assignment);
                _context.SaveChanges();

         //   return View();
             return RedirectToAction("Index",new { id=assignment.courseId});

        }

        // GET: Assignment/Edit/5
        public ActionResult Edit(int id)
        {
            var Assignment = _context.Assignments.SingleOrDefault(a => a.Id == id);

            return View(Assignment);
        }

        // POST: Assignment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Assignment assignment, HttpPostedFileBase uploadAssign)
        {
            try
            {
                // TODO: Add update logic here
                var assignInDb = _context.Assignments.SingleOrDefault(a => a.Id == assignment.Id);

                if (assignInDb == null)
                    return HttpNotFound();

                if (uploadAssign != null)
                {
                    string path = Path.Combine(Server.MapPath("~/upload/Assignments"), uploadAssign.FileName);
                    uploadAssign.SaveAs(path);
                    assignInDb.File = uploadAssign.FileName;
                }

                assignInDb.subject = assignment.subject;
                _context.SaveChanges();

                return RedirectToAction("Index", new { id = assignInDb.courseId });
            }
            catch
            {
                return View();
            }
        }

        // GET: Assignment/Delete/5
        public ActionResult Delete(int id)
        {

            var assignment = _context.Assignments.SingleOrDefault(a => a.Id == id);
            _context.Assignments.Remove(assignment);
            _context.SaveChanges();

            return RedirectToAction("Index",new { id=assignment.courseId});


            return View();
        }

        // POST: Assignment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Learning site/Controllers/StudentController.cs
using Learning_site.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Learning_site.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext _context;
        // GET: Student

        public StudentController()
        {
            _context = new ApplicationDbContext();

        }
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();
            var Courses = _context.EnrolledCourses.Where(c => c.StudentId == currentUserId).ToList();
            return View(Courses);

        }


        public ActionResult DisplayCourses()
        {
           
            var Courses = _context.Courses.ToList();

            return View(Courses);
        }


        public ActionResult CourseDetail(int id)
        {

            var course = _context.Courses.Include(a => a.instructor).SingleOrDefault(b => b.Id == id);
            Session["CourseId"] = id;
            return View(course);
        }



        
            public ActionResult EnrollInCourse(int id)
        {

            var currentUserId = User.Identity.GetUserId();
            // var CourseId = (int)Session["CourseId"];



            var EnrolledCourse =  _context.EnrolledCourses.Where(c => c.CourseId == id).SingleOrDefault(a=>a.StudentId == currentUserId);
           
            if (EnrolledCourse != null)
            {
              

                return Content("You are already enrolled in the course");

            }

            var enroll = new EnrolledCourse();
            enroll.CourseId = id;
            enroll.StudentId = currentUserId;

            _context.EnrolledCourses.Add(enroll);
            _context.SaveChanges();
            return View();
        }


        public ActionResult DisplayDetails()
        {
            string currentUserId = User.Identity.GetUserId();

            var Courses = _context.EnrolledCourses.Include(m => m.course).Include(m=>m.assignment).Where(c => c.StudentId == currentUserId).ToList();

            return View(Courses);
        }







        public ActionResult DisplayEnrolled()
        {
            string currentUserId = User.Identity.GetUserId();
            var Courses = _context.EnrolledCourses.Include(m=>m.course).Where(c => c.StudentId == currentUserId).ToList();

            return View(Courses);
        }




        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Learning site/Views/Student/CourseDetail.cshtml
@model Learning_site.Models.Course

@{
    ViewBag.Title = "CourseDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CourseDetail</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.instructor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.instructor.Name)
        </dd>


        <dd>
            <td>@Html.ActionLink(Model.name, "EnrollInCourse", "Student", new { id = Model.Id }, null)</td>
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Learning site/Views/Student/DisplayCourses.cshtml
@model IEnumerable<Learning_site.Models.Course>

@{
    ViewBag.Title = "DisplayCourses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayCourses</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
          <label>Instructor Name</label>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.instructor.Name)
        </td>
        <td>
            @Html.ActionLink("Enroll", "EnrollInCourse", new { id=item.Id })
      
        </td>
    </tr>
}

</table>

Learning site/Views/Student/DisplayDetails.cshtml
@model IEnumerable<Learning_site.Models.EnrolledCourse>

@{
    ViewBag.Title = "DisplayDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ALL student Courses</h2>




<table class="table">
    <tr>
        <th>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course.name)
            </td>
            
            <td>
               
                <a href="#">@Html.ActionLink("Show Assignmets", "Index", "Assignment", new { id = item.Id}, null)
</a>
            </td>
            
            <td>
             
            </td>




        </tr>
    }

</table>

Learning site/Views/Student/DisplayEnrolled.cshtml
@model IEnumerable<Learning_site.Models.EnrolledCourse>

@{
    ViewBag.Title = "DisplayEnrolled";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayEnrolled</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.course.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.course.name)
        </td>
        <td>
            @Html.ActionLink("Display Details", "DisplayDetails", new { id=item.StudentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.StudentId }) |

        </td>
    </tr>
}

</table>

Learning site/Views/Student/EnrollInCourse.cshtml
@model Learning_site.Models.EnrolledCourse
@{
    ViewBag.Title = "EnrollInCourse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>EnrollInCourse</h2>



<h3>You have been Enrolled in the course</h3>

<li><a href="#">@Html.ActionLink("Back To Courses", "DisplayCourses", "student")</a></li>

Learning site/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}







<h2>@Html.ActionLink("Display All Courses", "DisplayCourses", "Student", null, null)</h2>

<h2>
@Html.ActionLink("Display Enrolled Courses", "DisplayEnrolled", "Student", null, null)
</h2>